// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.Customer;

import java.util.List;


public interface CustomerDAO
{
  // CRUD methods
  public Customer getByPrimaryKey(int customerId) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Customer obj) throws DAOException;

  public int insert(Customer obj) throws DAOException;

  public int delete(Customer obj) throws DAOException;

  // Finders
  public List getByFirstName(String firstName) throws DAOException;

  public List getByLastName(String lastName) throws DAOException;

  public List getByAddress(String address) throws DAOException;

  public List getByIsSupplier(byte isSupplier) throws DAOException;
}
