// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

public class DAOException extends Exception
{
  public DAOException(String s, Exception e)
  {
    super(s, e);
  }

  public DAOException(String e)
  {
    super(e);
  }

  public DAOException(Exception e)
  {
    super(e);
  }
}
