// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.EmployeeHasTask;
import org.unibl.etf.dto.EmployeeHasTaskId;

import java.math.BigDecimal;

import java.util.Date;
import java.util.List;


public interface EmployeeHasTaskDAO
{
  // CRUD methods
  public EmployeeHasTask getByPrimaryKey(EmployeeHasTaskId id)
    throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(EmployeeHasTask obj) throws DAOException;

  public int insert(EmployeeHasTask obj) throws DAOException;

  public int delete(EmployeeHasTask obj) throws DAOException;

  // Finders
  public List getByDate(Date date) throws DAOException;

  public List getByTaskId(int taskId) throws DAOException;

  public List getByEmployeeId(int employeeId) throws DAOException;

  public List getByHourlyWage(BigDecimal hourlyWage) throws DAOException;

  public List getByHours(int hours) throws DAOException;

  public List getByPaidOff(byte paidOff) throws DAOException;
}
