// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.Event;

import java.sql.Clob;

import java.util.Date;
import java.util.List;


public interface EventDAO
{
  // CRUD methods
  public Event getByPrimaryKey(int eventId) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Event obj) throws DAOException;

  public int insert(Event obj) throws DAOException;

  public int delete(Event obj) throws DAOException;

  // Finders
  public List getByName(String name) throws DAOException;

  public List getByDescription(Clob description) throws DAOException;

  public List getByDate(Date date) throws DAOException;

  public List getByDone(byte done) throws DAOException;
}
