// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.Plant;

import java.sql.Blob;
import java.sql.Clob;

import java.util.List;


public interface PlantDAO
{
  // CRUD methods
  public Plant getByPrimaryKey(int plantId) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Plant obj) throws DAOException;

  public int insert(Plant obj) throws DAOException;

  public int delete(Plant obj) throws DAOException;

  // Finders
  public List getByScientificName(String scientificName)
    throws DAOException;

  public List getByKnownAs(String knownAs) throws DAOException;

  public List getByDescription(Clob description) throws DAOException;

  public List getByImage(Blob image) throws DAOException;

  public List getByOwned(byte owned) throws DAOException;
}
