// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.PricelistHasPlant;
import org.unibl.etf.dto.PricelistHasPlantId;

import java.util.List;


public interface PricelistHasPlantDAO
{
  // CRUD methods
  public PricelistHasPlant getByPrimaryKey(PricelistHasPlantId id)
    throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(PricelistHasPlant obj) throws DAOException;

  public int insert(PricelistHasPlant obj) throws DAOException;

  public int delete(PricelistHasPlant obj) throws DAOException;

  // Finders
  public List getByPricelistId(int pricelistId) throws DAOException;

  public List getByPlantId(int plantId) throws DAOException;
}
