// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.Purchase;

import java.math.BigDecimal;

import java.sql.Clob;

import java.util.Date;
import java.util.List;


public interface PurchaseDAO
{
  // CRUD methods
  public Purchase getByPrimaryKey(int purchaseId) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Purchase obj) throws DAOException;

  public int insert(Purchase obj) throws DAOException;

  public int delete(Purchase obj) throws DAOException;

  // Finders
  public List getByDate(Date date) throws DAOException;

  public List getByDescription(Clob description) throws DAOException;

  public List getByPrice(BigDecimal price) throws DAOException;

  public List getByPaidOff(byte paidOff) throws DAOException;

  public List getByCustomerId(int customerId) throws DAOException;
}
