// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.Sale;

import java.math.BigDecimal;

import java.util.Date;
import java.util.List;


public interface SaleDAO
{
  // CRUD methods
  public Sale getByPrimaryKey(int saleId) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Sale obj) throws DAOException;

  public int insert(Sale obj) throws DAOException;

  public int delete(Sale obj) throws DAOException;

  // Finders
  public List getByDate(Date date) throws DAOException;

  public List getByAmount(BigDecimal amount) throws DAOException;

  public List getByPaidOff(byte paidOff) throws DAOException;

  public List getByCustomerId(int customerId) throws DAOException;
}
