// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.Task;

import java.util.Date;
import java.util.List;


public interface TaskDAO
{
  // CRUD methods
  public Task getByPrimaryKey(int taskId) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Task obj) throws DAOException;

  public int insert(Task obj) throws DAOException;

  public int delete(Task obj) throws DAOException;

  // Finders
  public List getByDateFrom(Date dateFrom) throws DAOException;

  public List getByDateTo(Date dateTo) throws DAOException;

  public List getByDone(byte done) throws DAOException;

  public List getByRegionId(int regionId) throws DAOException;

  public List getByPlantMaintanceActivityId(int plantMaintanceActivityId)
    throws DAOException;
}
