// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.ToolItem;

import java.util.Date;
import java.util.List;


public interface ToolItemDAO
{
  // CRUD methods
  public ToolItem getByPrimaryKey(int toolItemId) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(ToolItem obj) throws DAOException;

  public int insert(ToolItem obj) throws DAOException;

  public int delete(ToolItem obj) throws DAOException;

  // Finders
  public List getByNextServiceDate(Date nextServiceDate)
    throws DAOException;

  public List getByIsMachine(byte isMachine) throws DAOException;

  public List getByToolId(int toolId) throws DAOException;

  public List getByConditionId(int conditionId) throws DAOException;
}
