// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.Transaction;

import java.math.BigDecimal;

import java.util.List;


public interface TransactionDAO
{
  // CRUD methods
  public Transaction getByPrimaryKey(int transactionId)
    throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Transaction obj) throws DAOException;

  public int insert(Transaction obj) throws DAOException;

  public int delete(Transaction obj) throws DAOException;

  // Finders
  public List getByAmount(BigDecimal amount) throws DAOException;

  public List getByType(byte type) throws DAOException;
}
