// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.util.Date;


public class Basis
{
  private int basisId;
  private Date plantingDate;
  private int produced;
  private int takeARoot;
  private byte active;
  private int plantId;

  //
  // getters / setters
  //
  public int getBasisId()
  {
    return this.basisId;
  }

  public void setBasisId(int basisId)
  {
    this.basisId = basisId;
  }

  public Date getPlantingDate()
  {
    return this.plantingDate;
  }

  public void setPlantingDate(Date plantingDate)
  {
    this.plantingDate = plantingDate;
  }

  public int getProduced()
  {
    return this.produced;
  }

  public void setProduced(int produced)
  {
    this.produced = produced;
  }

  public int getTakeARoot()
  {
    return this.takeARoot;
  }

  public void setTakeARoot(int takeARoot)
  {
    this.takeARoot = takeARoot;
  }

  public byte getActive()
  {
    return this.active;
  }

  public void setActive(byte active)
  {
    this.active = active;
  }

  public int getPlantId()
  {
    return this.plantId;
  }

  public void setPlantId(int plantId)
  {
    this.plantId = plantId;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Basis == false)
    {
      return false;
    }

    Basis other = (Basis) obj;

    if (basisId != other.basisId)
    {
      return false;
    }

    if (false == plantingDate.equals(other.plantingDate))
    {
      return false;
    }

    if (produced != other.produced)
    {
      return false;
    }

    if (takeARoot != other.takeARoot)
    {
      return false;
    }

    if (active != other.active)
    {
      return false;
    }

    if (plantId != other.plantId)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + basisId;
    result = (29 * result) + plantingDate.hashCode();
    result = (29 * result) + produced;
    result = (29 * result) + takeARoot;
    result = (29 * result) + (int) active;
    result = (29 * result) + plantId;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Basis").append("(");

    buffer.append("[").append("basisId").append("=").append(basisId).append("]");
    buffer.append("[").append("plantingDate").append("=").append(plantingDate).append("]");
    buffer.append("[").append("produced").append("=").append(produced).append("]");
    buffer.append("[").append("takeARoot").append("=").append(takeARoot).append("]");
    buffer.append("[").append("active").append("=").append(active).append("]");
    buffer.append("[").append("plantId").append("=").append(plantId).append("]");

    return buffer.append(")").toString();
  }
}
