// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class Customer
{
  private int customerId;
  private String firstName;
  private String lastName;
  private String address;
  private byte isSupplier;

  //
  // getters / setters
  //
  public int getCustomerId()
  {
    return this.customerId;
  }

  public void setCustomerId(int customerId)
  {
    this.customerId = customerId;
  }

  public String getFirstName()
  {
    return this.firstName;
  }

  public void setFirstName(String firstName)
  {
    this.firstName = firstName;
  }

  public String getLastName()
  {
    return this.lastName;
  }

  public void setLastName(String lastName)
  {
    this.lastName = lastName;
  }

  public String getAddress()
  {
    return this.address;
  }

  public void setAddress(String address)
  {
    this.address = address;
  }

  public byte getIsSupplier()
  {
    return this.isSupplier;
  }

  public void setIsSupplier(byte isSupplier)
  {
    this.isSupplier = isSupplier;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Customer == false)
    {
      return false;
    }

    Customer other = (Customer) obj;

    if (customerId != other.customerId)
    {
      return false;
    }

    if (false == firstName.equals(other.firstName))
    {
      return false;
    }

    if (false == lastName.equals(other.lastName))
    {
      return false;
    }

    if (false == address.equals(other.address))
    {
      return false;
    }

    if (isSupplier != other.isSupplier)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + customerId;
    result = (29 * result) + firstName.hashCode();
    result = (29 * result) + lastName.hashCode();
    result = (29 * result) + address.hashCode();
    result = (29 * result) + (int) isSupplier;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Customer").append("(");

    buffer.append("[").append("customerId").append("=").append(customerId).append("]");
    buffer.append("[").append("firstName").append("=").append(firstName).append("]");
    buffer.append("[").append("lastName").append("=").append(lastName).append("]");
    buffer.append("[").append("address").append("=").append(address).append("]");
    buffer.append("[").append("isSupplier").append("=").append(isSupplier).append("]");

    return buffer.append(")").toString();
  }
}
