// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.math.BigDecimal;


public class EmployeeHasTask
{
  private EmployeeHasTaskId id;
  private BigDecimal hourlyWage;
  private int hours;
  private byte paidOff;

  //
  // getters / setters
  //
  public EmployeeHasTaskId getId()
  {
    return this.id;
  }

  public void setId(EmployeeHasTaskId id)
  {
    this.id = id;
  }

  public BigDecimal getHourlyWage()
  {
    return this.hourlyWage;
  }

  public void setHourlyWage(BigDecimal hourlyWage)
  {
    this.hourlyWage = hourlyWage;
  }

  public int getHours()
  {
    return this.hours;
  }

  public void setHours(int hours)
  {
    this.hours = hours;
  }

  public byte getPaidOff()
  {
    return this.paidOff;
  }

  public void setPaidOff(byte paidOff)
  {
    this.paidOff = paidOff;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof EmployeeHasTask == false)
    {
      return false;
    }

    EmployeeHasTask other = (EmployeeHasTask) obj;

    if (false == id.equals(other.id))
    {
      return false;
    }

    if (false == hourlyWage.equals(other.hourlyWage))
    {
      return false;
    }

    if (hours != other.hours)
    {
      return false;
    }

    if (paidOff != other.paidOff)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + id.hashCode();
    result = (29 * result) + hourlyWage.hashCode();
    result = (29 * result) + hours;
    result = (29 * result) + (int) paidOff;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("EmployeeHasTask")
                                                               .append("(");

    buffer.append("[").append("id").append("=").append(id).append("]");
    buffer.append("[").append("hourlyWage").append("=").append(hourlyWage).append("]");
    buffer.append("[").append("hours").append("=").append(hours).append("]");
    buffer.append("[").append("paidOff").append("=").append(paidOff).append("]");

    return buffer.append(")").toString();
  }
}
