// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class PricelistHasPlant
{
  private PricelistHasPlantId id;

  //
  // getters / setters
  //
  public PricelistHasPlantId getId()
  {
    return this.id;
  }

  public void setId(PricelistHasPlantId id)
  {
    this.id = id;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof PricelistHasPlant == false)
    {
      return false;
    }

    PricelistHasPlant other = (PricelistHasPlant) obj;

    if (false == id.equals(other.id))
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + id.hashCode();

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("PricelistHasPlant")
                                                               .append("(");

    buffer.append("[").append("id").append("=").append(id).append("]");

    return buffer.append(")").toString();
  }
}
