// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.math.BigDecimal;

import java.util.Date;


public class Sale
{
  private int saleId;
  private Date date;
  private BigDecimal amount;
  private byte paidOff;
  private int customerId;

  //
  // getters / setters
  //
  public int getSaleId()
  {
    return this.saleId;
  }

  public void setSaleId(int saleId)
  {
    this.saleId = saleId;
  }

  public Date getDate()
  {
    return this.date;
  }

  public void setDate(Date date)
  {
    this.date = date;
  }

  public BigDecimal getAmount()
  {
    return this.amount;
  }

  public void setAmount(BigDecimal amount)
  {
    this.amount = amount;
  }

  public byte getPaidOff()
  {
    return this.paidOff;
  }

  public void setPaidOff(byte paidOff)
  {
    this.paidOff = paidOff;
  }

  public int getCustomerId()
  {
    return this.customerId;
  }

  public void setCustomerId(int customerId)
  {
    this.customerId = customerId;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Sale == false)
    {
      return false;
    }

    Sale other = (Sale) obj;

    if (saleId != other.saleId)
    {
      return false;
    }

    if (false == date.equals(other.date))
    {
      return false;
    }

    if (false == amount.equals(other.amount))
    {
      return false;
    }

    if (paidOff != other.paidOff)
    {
      return false;
    }

    if (customerId != other.customerId)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + saleId;
    result = (29 * result) + date.hashCode();
    result = (29 * result) + amount.hashCode();
    result = (29 * result) + (int) paidOff;
    result = (29 * result) + customerId;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Sale").append("(");

    buffer.append("[").append("saleId").append("=").append(saleId).append("]");
    buffer.append("[").append("date").append("=").append(date).append("]");
    buffer.append("[").append("amount").append("=").append(amount).append("]");
    buffer.append("[").append("paidOff").append("=").append(paidOff).append("]");
    buffer.append("[").append("customerId").append("=").append(customerId).append("]");

    return buffer.append(")").toString();
  }
}
