// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.io.Serializable;

import java.util.Date;


public class ToolMaintanceActivityId implements Serializable
{
  private Date date;
  private int toolItemId;

  //
  // getters / setters
  //
  public Date getDate()
  {
    return this.date;
  }

  public void setDate(Date date)
  {
    this.date = date;
  }

  public int getToolItemId()
  {
    return this.toolItemId;
  }

  public void setToolItemId(int toolItemId)
  {
    this.toolItemId = toolItemId;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof ToolMaintanceActivityId == false)
    {
      return false;
    }

    ToolMaintanceActivityId other = (ToolMaintanceActivityId) obj;

    if (false == date.equals(other.date))
    {
      return false;
    }

    if (toolItemId != other.toolItemId)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + date.hashCode();
    result = (29 * result) + toolItemId;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("ToolMaintanceActivityId")
                                                               .append("(");

    buffer.append("[").append("date").append("=").append(date).append("]");
    buffer.append("[").append("toolItemId").append("=").append(toolItemId).append("]");

    return buffer.append(")").toString();
  }
}
