// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.math.BigDecimal;

import java.sql.Clob;


public class ToolMaintanceActivity
{
  private ToolMaintanceActivityId id;
  private Clob description;
  private BigDecimal amount;

  //
  // getters / setters
  //
  public ToolMaintanceActivityId getId()
  {
    return this.id;
  }

  public void setId(ToolMaintanceActivityId id)
  {
    this.id = id;
  }

  public Clob getDescription()
  {
    return this.description;
  }

  public void setDescription(Clob description)
  {
    this.description = description;
  }

  public BigDecimal getAmount()
  {
    return this.amount;
  }

  public void setAmount(BigDecimal amount)
  {
    this.amount = amount;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof ToolMaintanceActivity == false)
    {
      return false;
    }

    ToolMaintanceActivity other = (ToolMaintanceActivity) obj;

    if (false == id.equals(other.id))
    {
      return false;
    }

    if (false == description.equals(other.description))
    {
      return false;
    }

    if (false == amount.equals(other.amount))
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + id.hashCode();
    result = (29 * result) + description.hashCode();
    result = (29 * result) + amount.hashCode();

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("ToolMaintanceActivity")
                                                               .append("(");

    buffer.append("[").append("id").append("=").append(id).append("]");
    buffer.append("[").append("description").append("=").append(description).append("]");
    buffer.append("[").append("amount").append("=").append(amount).append("]");

    return buffer.append(")").toString();
  }
}
