// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.Employee;

import java.util.List;


public interface EmployeeDAO
{
  // CRUD methods
  public Employee getByPrimaryKey(int employeeId) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Employee obj) throws DAOException;

  public int insert(Employee obj) throws DAOException;

  public int delete(Employee obj) throws DAOException;

  // Finders
  public List getByFirstName(String firstName) throws DAOException;

  public List getByLastName(String lastName) throws DAOException;
}
