// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.PriceHeightRatio;
import org.unibl.etf.dto.PriceHeightRatioId;

import java.math.BigDecimal;

import java.util.Date;
import java.util.List;


public interface PriceHeightRatioDAO
{
  // CRUD methods
  public PriceHeightRatio getByPrimaryKey(PriceHeightRatioId id)
    throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(PriceHeightRatio obj) throws DAOException;

  public int insert(PriceHeightRatio obj) throws DAOException;

  public int delete(PriceHeightRatio obj) throws DAOException;

  // Finders
  public List getByDateFrom(Date dateFrom) throws DAOException;

  public List getByPlantId(int plantId) throws DAOException;

  public List getByHeightMin(BigDecimal heightMin) throws DAOException;

  public List getByHeightMax(BigDecimal heightMax) throws DAOException;

  public List getByPrice(BigDecimal price) throws DAOException;

  public List getByActive(byte active) throws DAOException;
}
