// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import java.util.List;

import org.unibl.etf.dto.PricelistHasPlant;

public interface PricelistHasPlantDAO {
	// CRUD methods
	public PricelistHasPlant getByPrimaryKey(Integer idPricelist, Integer plantId);

	public List<PricelistHasPlant> selectAll();

	public List<PricelistHasPlant> select(String whereStatement, Object[] bindVariables);

	public Long selectCount();

	public Long selectCount(String whereStatement, Object[] bindVariables);

	public Integer update(PricelistHasPlant obj);

	public Integer insert(PricelistHasPlant obj);

	public Integer delete(PricelistHasPlant obj);

	// Finders
	public List<PricelistHasPlant> getByPricelistId(Integer pricelistId);

	public List<PricelistHasPlant> getByPlantId(Integer plantId);
}
