// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.unibl.etf.dto.Purchase;

public interface PurchaseDAO {
	// CRUD methods
	public Purchase getByPrimaryKey(Integer purchaseId) ;

	public List<Purchase> selectAll() ;

	public List<Purchase> select(String whereStatement, Object[] bindVariables) ;

	public Long selectCount() ;

	public Long selectCount(String whereStatement, Object[] bindVariables) ;

	public Integer update(Purchase obj) ;

	public Integer insert(Purchase obj) ;

	public Integer delete(Purchase obj) ;

	// Finders
	public List<Purchase> getByDate(Date date) ;

	public List<Purchase> getByDescription(String description) ;

	public List<Purchase> getByPrice(BigDecimal price) ;

	public List<Purchase> getByPaidOff(Boolean paidOff) ;
	
	public List<Purchase> getByDeleted(Boolean deleted) ;

	public List<Purchase> getByCustomerId(Integer customerId);
}
