// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.Region;

import java.util.List;


public interface RegionDAO
{
  // CRUD methods
  public Region getByPrimaryKey(int regionId) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Region obj) throws DAOException;

  public int insert(Region obj) throws DAOException;

  public int delete(Region obj) throws DAOException;

  // Finders
  public List getByNumberOfPlants(int numberOfPlants) throws DAOException;

  public List getByBasisId(int basisId) throws DAOException;
}
