// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.ReproductionCutting;
import org.unibl.etf.dto.ReproductionCuttingId;

import java.util.Date;
import java.util.List;


public interface ReproductionCuttingDAO
{
  // CRUD methods
  public ReproductionCutting getByPrimaryKey(ReproductionCuttingId id)
    throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(ReproductionCutting obj) throws DAOException;

  public int insert(ReproductionCutting obj) throws DAOException;

  public int delete(ReproductionCutting obj) throws DAOException;

  // Finders
  public List getByBasisId(int basisId) throws DAOException;

  public List getByDate(Date date) throws DAOException;
}
