// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import java.util.Date;
import java.util.List;

import org.unibl.etf.dto.ReproductionCutting;

public interface ReproductionCuttingDAO {
	// CRUD methods
	public ReproductionCutting getByPrimaryKey(Integer idBasis, Date date);

	public List<ReproductionCutting> selectAll();

	public List<ReproductionCutting> select(String whereStatement, Object[] bindVariables);

	public Long selectCount();

	public Long selectCount(String whereStatement, Object[] bindVariables);

	public Integer update(ReproductionCutting obj);

	public Integer insert(ReproductionCutting obj);

	public Integer delete(ReproductionCutting obj);

	// Finders
	public List<ReproductionCutting> getByBasisId(Integer basisId);

	public List<ReproductionCutting> getByDate(Date date);
}
