// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;


import org.unibl.etf.dto.ReproductionCutting;


import java.util.Date;
import java.util.List;


public interface ReproductionCuttingDAO
{
  // CRUD methods
  public ReproductionCutting getByPrimaryKey(Integer idBasis,Date date)
    throws DAOException;

  public List<ReproductionCutting> selectAll() throws DAOException;

  public List<ReproductionCutting> select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public Long selectCount() throws DAOException;

  public Long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public Integer update(ReproductionCutting obj) throws DAOException;

  public Integer insert(ReproductionCutting obj) throws DAOException;

  public Integer delete(ReproductionCutting obj) throws DAOException;

  // Finders
  public List<ReproductionCutting> getByBasisId(Integer basisId) throws DAOException;

  public List<ReproductionCutting> getByDate(Date date) throws DAOException;
}
