// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import java.math.BigDecimal;
import java.util.List;

import org.unibl.etf.dto.SaleItem;

public interface SaleItemDAO {
	// CRUD methods
	public SaleItem getByPrimaryKey(Integer idSale, Integer idPlant, BigDecimal heightMin);

	public List<SaleItem> selectAll();

	public List<SaleItem> select(String whereStatement, Object[] bindVariables);

	public Long selectCount();

	public Long selectCount(String whereStatement, Object[] bindVariables);

	public Integer update(SaleItem obj);

	public Integer insert(SaleItem obj);

	public Integer delete(SaleItem obj);

	// Finders

	public List<SaleItem> getByPlantId(Integer plantId);

	public List<SaleItem> getBySaleId(Integer saleId);

	public List<SaleItem> getByCount(Integer count);
}
