// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import java.util.List;

import org.unibl.etf.dto.SaleItem;

public interface SaleItemDAO {
	// CRUD methods
	public SaleItem getByPrimaryKey(Integer idSale, Integer idPricelist, Integer idPlant) throws DAOException;

	public List<SaleItem> selectAll() throws DAOException;

	public List<SaleItem> select(String whereStatement, Object[] bindVariables) throws DAOException;

	public Long selectCount() throws DAOException;

	public Long selectCount(String whereStatement, Object[] bindVariables) throws DAOException;

	public Integer update(SaleItem obj) throws DAOException;

	public Integer insert(SaleItem obj) throws DAOException;

	public Integer delete(SaleItem obj) throws DAOException;

	// Finders
	public List<SaleItem> getByPricelistId(Integer pricelistId) throws DAOException;

	public List<SaleItem> getByPlantId(Integer plantId) throws DAOException;

	public List<SaleItem> getBySaleId(Integer saleId) throws DAOException;

	public List<SaleItem> getByCount(Integer count) throws DAOException;
}
