// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;


import java.util.Date;
import java.util.List;

import org.unibl.etf.dto.Task;


public interface TaskDAO
{
  // CRUD methods
  public Task getByPrimaryKey(Integer taskId) throws DAOException;

  public List<Task> selectAll() throws DAOException;

  public List<Task> select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public Long selectCount() throws DAOException;

  public Long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public Integer update(Task obj) throws DAOException;

  public Integer insert(Task obj) throws DAOException;

  public Integer delete(Task obj) throws DAOException;

  // Finders
  public List<Task> getByDateFrom(Date dateFrom) throws DAOException;

  public List<Task> getByDateTo(Date dateTo) throws DAOException;

  public List<Task> getByDone(Boolean done) throws DAOException;

  public List<Task> getByRegionId(Integer regionId) throws DAOException;

  public List<Task> getByPlantMaintanceActivityId(Integer plantMaintanceActivityId)
    throws DAOException;
}
