// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import java.util.Date;
import java.util.List;


import org.unibl.etf.dto.ToolItem;

public interface ToolItemDAO {
	// CRUD methods
	public ToolItem getByPrimaryKey(Integer toolItemId);

	public List<ToolItem> selectAll();

	public List<ToolItem> select(String whereStatement, Object[] bindVariables);

	public Long selectCount();

	public Long selectCount(String whereStatement, Object[] bindVariables);

	public Integer update(ToolItem obj);

	public Integer insert(ToolItem obj);

	public Integer delete(ToolItem obj);

	// Finders
	public List<ToolItem> getByNextServiceDate(Date nextServiceDate);

	public List<ToolItem> getByToolId(Integer toolId);

	public List<ToolItem> getByConditionId(Integer conditionId);
	
	public List<ToolItem> getByIsDeleted(Boolean isDeleted);
}
