// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.Tool;

import java.util.List;


public interface ToolDAO
{
  // CRUD methods
  public Tool getByPrimaryKey(int toolId) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Tool obj) throws DAOException;

  public int insert(Tool obj) throws DAOException;

  public int delete(Tool obj) throws DAOException;

  // Finders
  public List getByToolName(String toolName) throws DAOException;

  public List getByCount(int count) throws DAOException;
}
