// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.ToolItem;
import org.unibl.etf.dto.ToolMaintanceActivity;

import java.math.BigDecimal;

import java.sql.Clob;

import java.util.Date;
import java.util.List;


public interface ToolMaintanceActivityDAO
{
  // CRUD methods
  public ToolMaintanceActivity getByPrimaryKey(ToolItem idToolItem,Date date)
    throws DAOException;

  public List<ToolMaintanceActivity> selectAll() throws DAOException;

  public List<ToolMaintanceActivity> select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public Long selectCount() throws DAOException;

  public Long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public Integer update(ToolMaintanceActivity obj) throws DAOException;

  public Integer insert(ToolMaintanceActivity obj) throws DAOException;

  public Integer delete(ToolMaintanceActivity obj) throws DAOException;

  // Finders
  public List<ToolMaintanceActivity> getByDate(Date date) throws DAOException;

  public List<ToolMaintanceActivity> getByToolItemId(ToolItem toolItemId) throws DAOException;

  public List<ToolMaintanceActivity> getByDescription(Clob description) throws DAOException;

  public List<ToolMaintanceActivity> getByAmount(BigDecimal amount) throws DAOException;
}
