// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import org.unibl.etf.dto.ToolMaintanceActivity;
import org.unibl.etf.dto.ToolMaintanceActivityId;

import java.math.BigDecimal;

import java.sql.Clob;

import java.util.Date;
import java.util.List;


public interface ToolMaintanceActivityDAO
{
  // CRUD methods
  public ToolMaintanceActivity getByPrimaryKey(ToolMaintanceActivityId id)
    throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(ToolMaintanceActivity obj) throws DAOException;

  public int insert(ToolMaintanceActivity obj) throws DAOException;

  public int delete(ToolMaintanceActivity obj) throws DAOException;

  // Finders
  public List getByDate(Date date) throws DAOException;

  public List getByToolItemId(int toolItemId) throws DAOException;

  public List getByDescription(Clob description) throws DAOException;

  public List getByAmount(BigDecimal amount) throws DAOException;
}
