// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dao.interfaces;

import java.math.BigDecimal;
import java.util.List;

import org.unibl.etf.dto.Transaction;

public interface TransactionDAO {
	// CRUD methods
	public Transaction getByPrimaryKey(Integer transactionId);

	public List<Transaction> selectAll();

	public List<Transaction> select(String whereStatement, Object[] bindVariables);

	public Long selectCount();

	public Long selectCount(String whereStatement, Object[] bindVariables);

	public Integer update(Transaction obj);

	public Integer insert(Transaction obj);

	public Integer delete(Transaction obj);

	// Finders
	public List<Transaction> getByAmount(BigDecimal amount);

	public List<Transaction> getByType(Boolean type);

	public List<Transaction> getByDescription(String description);
	
	public List<Transaction> getByDeleted(Boolean deleted);
}
