package org.unibl.etf.gui.plants.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;

import org.unibl.etf.dao.interfaces.DAOFactory;
import org.unibl.etf.dto.Basis;
import org.unibl.etf.dto.Region;
import org.unibl.etf.gui.util.DisplayUtil;
import org.unibl.etf.gui.view.base.BaseController;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class AddRegionController extends BaseController {
	@FXML
	private ComboBox<Basis> cbBasis;
	@FXML
	private Button btnAddBasis;
	@FXML
	private TextField txtPlantsNum;
	@FXML
	private Button btnSave;

	// Event Listener on Button[#btnAddBasis].onAction
	@FXML
	public void addBasis(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnSave].onAction
	@FXML
	public void save(ActionEvent event) {
		try {
			Integer numberOfPlants = Integer.parseInt(txtPlantsNum.getText());
			region.setBasis(cbBasis.getSelectionModel().getSelectedItem());
			region.setBasisId(cbBasis.getSelectionModel().getSelectedItem().getBasisId());
			region.setNumberOfPlants(numberOfPlants);
			DisplayUtil.close(btnSave);
		} catch(NumberFormatException ex) {
			DisplayUtil.showMessageDialog("Format podataka nije ispravan!");
		}
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		List<Basis> bases = DAOFactory.getInstance().getBasisDAO().selectAll();
		ObservableList<Basis> cbItems = FXCollections.observableArrayList();
		cbItems.addAll(bases);
		cbBasis.setItems(cbItems);
		cbBasis.getSelectionModel().select(0);
		bindDisable();
	}

	public Region getRegion() {
		return region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	private Region region;

	private void bindDisable() {
		btnSave.disableProperty().bind(txtPlantsNum.textProperty().isEmpty());
	}
}
