// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class Condition
{
  private int conditionId;
  private String condition;

  //
  // getters / setters
  //
  public int getConditionId()
  {
    return this.conditionId;
  }

  public void setConditionId(int conditionId)
  {
    this.conditionId = conditionId;
  }

  public String getCondition()
  {
    return this.condition;
  }

  public void setCondition(String condition)
  {
    this.condition = condition;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Condition == false)
    {
      return false;
    }

    Condition other = (Condition) obj;

    if (conditionId != other.conditionId)
    {
      return false;
    }

    if (false == condition.equals(other.condition))
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + conditionId;
    result = (29 * result) + condition.hashCode();

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Condition").append("(");

    buffer.append("[").append("conditionId").append("=").append(conditionId).append("]");
    buffer.append("[").append("condition").append("=").append(condition).append("]");

    return buffer.append(")").toString();
  }
}
