// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.io.Serializable;

import java.util.Date;


public class EmployeeHasTaskId implements Serializable
{
  private Date date;
  private int taskId;
  private int employeeId;

  //
  // getters / setters
  //
  public Date getDate()
  {
    return this.date;
  }

  public void setDate(Date date)
  {
    this.date = date;
  }

  public int getTaskId()
  {
    return this.taskId;
  }

  public void setTaskId(int taskId)
  {
    this.taskId = taskId;
  }

  public int getEmployeeId()
  {
    return this.employeeId;
  }

  public void setEmployeeId(int employeeId)
  {
    this.employeeId = employeeId;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof EmployeeHasTaskId == false)
    {
      return false;
    }

    EmployeeHasTaskId other = (EmployeeHasTaskId) obj;

    if (false == date.equals(other.date))
    {
      return false;
    }

    if (taskId != other.taskId)
    {
      return false;
    }

    if (employeeId != other.employeeId)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + date.hashCode();
    result = (29 * result) + taskId;
    result = (29 * result) + employeeId;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("EmployeeHasTaskId")
                                                               .append("(");

    buffer.append("[").append("date").append("=").append(date).append("]");
    buffer.append("[").append("taskId").append("=").append(taskId).append("]");
    buffer.append("[").append("employeeId").append("=").append(employeeId).append("]");

    return buffer.append(")").toString();
  }
}
