// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class Employee
{
  private Integer employeeId;
  private String firstName;
  private String lastName;
  
  

  public Employee() {
	super();
}

public Employee(Integer employeeId, String firstName, String lastName) {
	super();
	this.employeeId = employeeId;
	this.firstName = firstName;
	this.lastName = lastName;
}

//
  // getters / setters
  //
  public Integer getEmployeeId()
  {
    return this.employeeId;
  }

  public void setEmployeeId(Integer employeeId)
  {
    this.employeeId = employeeId;
  }

  public String getFirstName()
  {
    return this.firstName;
  }

  public void setFirstName(String firstName)
  {
    this.firstName = firstName;
  }

  public String getLastName()
  {
    return this.lastName;
  }

  public void setLastName(String lastName)
  {
    this.lastName = lastName;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Employee == false)
    {
      return false;
    }

    Employee other = (Employee) obj;

    if (employeeId != other.employeeId)
    {
      return false;
    }

    if (false == firstName.equals(other.firstName))
    {
      return false;
    }

    if (false == lastName.equals(other.lastName))
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + employeeId;
    result = (29 * result) + firstName.hashCode();
    result = (29 * result) + lastName.hashCode();

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Employee").append("(");

    buffer.append("[").append("employeeId").append("=").append(employeeId).append("]");
    buffer.append("[").append("firstName").append("=").append(firstName).append("]");
    buffer.append("[").append("lastName").append("=").append(lastName).append("]");

    return buffer.append(")").toString();
  }
}
