// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.sql.Clob;

import java.util.Date;


public class Event
{
  private int eventId;
  private String name;
  private Clob description;
  private Date date;
  private byte done;

  //
  // getters / setters
  //
  public int getEventId()
  {
    return this.eventId;
  }

  public void setEventId(int eventId)
  {
    this.eventId = eventId;
  }

  public String getName()
  {
    return this.name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

  public Clob getDescription()
  {
    return this.description;
  }

  public void setDescription(Clob description)
  {
    this.description = description;
  }

  public Date getDate()
  {
    return this.date;
  }

  public void setDate(Date date)
  {
    this.date = date;
  }

  public byte getDone()
  {
    return this.done;
  }

  public void setDone(byte done)
  {
    this.done = done;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Event == false)
    {
      return false;
    }

    Event other = (Event) obj;

    if (eventId != other.eventId)
    {
      return false;
    }

    if (false == name.equals(other.name))
    {
      return false;
    }

    if (false == description.equals(other.description))
    {
      return false;
    }

    if (false == date.equals(other.date))
    {
      return false;
    }

    if (done != other.done)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + eventId;
    result = (29 * result) + name.hashCode();
    result = (29 * result) + description.hashCode();
    result = (29 * result) + date.hashCode();
    result = (29 * result) + (int) done;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Event").append("(");

    buffer.append("[").append("eventId").append("=").append(eventId).append("]");
    buffer.append("[").append("name").append("=").append(name).append("]");
    buffer.append("[").append("description").append("=").append(description).append("]");
    buffer.append("[").append("date").append("=").append(date).append("]");
    buffer.append("[").append("done").append("=").append(done).append("]");

    return buffer.append(")").toString();
  }
}
