// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class PlantMaintanceActivity
{
  private int plantMaintanceActivityId;
  private String activity;
  private byte plant;

  //
  // getters / setters
  //
  public int getPlantMaintanceActivityId()
  {
    return this.plantMaintanceActivityId;
  }

  public void setPlantMaintanceActivityId(int plantMaintanceActivityId)
  {
    this.plantMaintanceActivityId = plantMaintanceActivityId;
  }

  public String getActivity()
  {
    return this.activity;
  }

  public void setActivity(String activity)
  {
    this.activity = activity;
  }

  public byte getPlant()
  {
    return this.plant;
  }

  public void setPlant(byte plant)
  {
    this.plant = plant;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof PlantMaintanceActivity == false)
    {
      return false;
    }

    PlantMaintanceActivity other = (PlantMaintanceActivity) obj;

    if (plantMaintanceActivityId != other.plantMaintanceActivityId)
    {
      return false;
    }

    if (false == activity.equals(other.activity))
    {
      return false;
    }

    if (plant != other.plant)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + plantMaintanceActivityId;
    result = (29 * result) + activity.hashCode();
    result = (29 * result) + (int) plant;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("PlantMaintanceActivity")
                                                               .append("(");

    buffer.append("[").append("plantMaintanceActivityId").append("=").append(plantMaintanceActivityId)
          .append("]");
    buffer.append("[").append("activity").append("=").append(activity).append("]");
    buffer.append("[").append("plant").append("=").append(plant).append("]");

    return buffer.append(")").toString();
  }
}
