// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.sql.Blob;
import java.sql.Clob;


public class Plant
{
  private int plantId;
  private String scientificName;
  private String knownAs;
  private Clob description;
  private Blob image;
  private byte owned;

  //
  // getters / setters
  //
  public int getPlantId()
  {
    return this.plantId;
  }

  public void setPlantId(int plantId)
  {
    this.plantId = plantId;
  }

  public String getScientificName()
  {
    return this.scientificName;
  }

  public void setScientificName(String scientificName)
  {
    this.scientificName = scientificName;
  }

  public String getKnownAs()
  {
    return this.knownAs;
  }

  public void setKnownAs(String knownAs)
  {
    this.knownAs = knownAs;
  }

  public Clob getDescription()
  {
    return this.description;
  }

  public void setDescription(Clob description)
  {
    this.description = description;
  }

  public Blob getImage()
  {
    return this.image;
  }

  public void setImage(Blob image)
  {
    this.image = image;
  }

  public byte getOwned()
  {
    return this.owned;
  }

  public void setOwned(byte owned)
  {
    this.owned = owned;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Plant == false)
    {
      return false;
    }

    Plant other = (Plant) obj;

    if (plantId != other.plantId)
    {
      return false;
    }

    if (false == scientificName.equals(other.scientificName))
    {
      return false;
    }

    if (false == knownAs.equals(other.knownAs))
    {
      return false;
    }

    if (false == description.equals(other.description))
    {
      return false;
    }

    if (false == image.equals(other.image))
    {
      return false;
    }

    if (owned != other.owned)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + plantId;
    result = (29 * result) + scientificName.hashCode();
    result = (29 * result) + knownAs.hashCode();
    result = (29 * result) + description.hashCode();
    result = (29 * result) + image.hashCode();
    result = (29 * result) + (int) owned;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Plant").append("(");

    buffer.append("[").append("plantId").append("=").append(plantId).append("]");
    buffer.append("[").append("scientificName").append("=").append(scientificName).append("]");
    buffer.append("[").append("knownAs").append("=").append(knownAs).append("]");
    buffer.append("[").append("description").append("=").append(description).append("]");
    buffer.append("[").append("image").append("=").append(image).append("]");
    buffer.append("[").append("owned").append("=").append(owned).append("]");

    return buffer.append(")").toString();
  }
}
