// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.util.Date;


public class Pricelist
{
  private int pricelistId;
  private Date dateFrom;
  private Date dateTo;
  private byte active;

  //
  // getters / setters
  //
  public int getPricelistId()
  {
    return this.pricelistId;
  }

  public void setPricelistId(int pricelistId)
  {
    this.pricelistId = pricelistId;
  }

  public Date getDateFrom()
  {
    return this.dateFrom;
  }

  public void setDateFrom(Date dateFrom)
  {
    this.dateFrom = dateFrom;
  }

  public Date getDateTo()
  {
    return this.dateTo;
  }

  public void setDateTo(Date dateTo)
  {
    this.dateTo = dateTo;
  }

  public byte getActive()
  {
    return this.active;
  }

  public void setActive(byte active)
  {
    this.active = active;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Pricelist == false)
    {
      return false;
    }

    Pricelist other = (Pricelist) obj;

    if (pricelistId != other.pricelistId)
    {
      return false;
    }

    if (false == dateFrom.equals(other.dateFrom))
    {
      return false;
    }

    if (false == dateTo.equals(other.dateTo))
    {
      return false;
    }

    if (active != other.active)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + pricelistId;
    result = (29 * result) + dateFrom.hashCode();
    result = (29 * result) + dateTo.hashCode();
    result = (29 * result) + (int) active;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Pricelist").append("(");

    buffer.append("[").append("pricelistId").append("=").append(pricelistId).append("]");
    buffer.append("[").append("dateFrom").append("=").append(dateFrom).append("]");
    buffer.append("[").append("dateTo").append("=").append(dateTo).append("]");
    buffer.append("[").append("active").append("=").append(active).append("]");

    return buffer.append(")").toString();
  }
}
