// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.io.Serializable;

import java.util.Date;


public class PriceHeightRatioId implements Serializable
{
  private Date dateFrom;
  private int plantId;

  //
  // getters / setters
  //
  public Date getDateFrom()
  {
    return this.dateFrom;
  }

  public void setDateFrom(Date dateFrom)
  {
    this.dateFrom = dateFrom;
  }

  public int getPlantId()
  {
    return this.plantId;
  }

  public void setPlantId(int plantId)
  {
    this.plantId = plantId;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof PriceHeightRatioId == false)
    {
      return false;
    }

    PriceHeightRatioId other = (PriceHeightRatioId) obj;

    if (false == dateFrom.equals(other.dateFrom))
    {
      return false;
    }

    if (plantId != other.plantId)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + dateFrom.hashCode();
    result = (29 * result) + plantId;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("PriceHeightRatioId")
                                                               .append("(");

    buffer.append("[").append("dateFrom").append("=").append(dateFrom).append("]");
    buffer.append("[").append("plantId").append("=").append(plantId).append("]");

    return buffer.append(")").toString();
  }
}
