// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class Region
{
  private Integer regionId;
  private Integer numberOfPlants;
  private Basis basis;

  //
  // getters / setters
  //
  public Integer getRegionId()
  {
    return this.regionId;
  }

  public void setRegionId(Integer regionId)
  {
    this.regionId = regionId;
  }

  public Integer getNumberOfPlants()
  {
    return this.numberOfPlants;
  }

  public void setNumberOfPlants(Integer numberOfPlants)
  {
    this.numberOfPlants = numberOfPlants;
  }

  public Basis getBasis()
  {
    return this.basis;
  }

  public void setBasis(Basis basis)
  {
    this.basis = basis;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Region == false)
    {
      return false;
    }

    Region other = (Region) obj;

    if (regionId != other.regionId)
    {
      return false;
    }

    if (numberOfPlants != other.numberOfPlants)
    {
      return false;
    }

    if (basis != other.basis)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + regionId;
    result = (29 * result) + numberOfPlants;
    result = (29 * result) + basis.hashCode();

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Region").append("(");

    buffer.append("[").append("regionId").append("=").append(regionId).append("]");
    buffer.append("[").append("numberOfPlants").append("=").append(numberOfPlants).append("]");
    buffer.append("[").append("basisId").append("=").append(basis).append("]");

    return buffer.append(")").toString();
  }
}
