// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class Region {
	private Integer regionId;
	private Integer numberOfPlants;
	private Basis basis;
	private Integer basisId;

	//
	// getters / setters
	//
	public Integer getBasisId() {
		return basisId;
	}

	public void setBasisId(Integer basisId) {
		this.basisId = basisId;
	}

	public Integer getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	public Integer getNumberOfPlants() {
		return this.numberOfPlants;
	}

	public void setNumberOfPlants(Integer numberOfPlants) {
		this.numberOfPlants = numberOfPlants;
	}

	public Basis getBasis() {
		return this.basis;
	}

	public void setBasis(Basis basis) {
		this.basis = basis;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((regionId == null) ? 0 : regionId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Region other = (Region) obj;
		if (regionId == null) {
			if (other.regionId != null)
				return false;
		} else if (!regionId.equals(other.regionId))
			return false;
		return true;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Region").append("(");

		buffer.append("[").append("regionId").append("=").append(regionId).append("]");
		buffer.append("[").append("numberOfPlants").append("=").append(numberOfPlants).append("]");
		buffer.append("[").append("basisId").append("=").append(basis).append("]");

		return buffer.append(")").toString();
	}
}
