// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.util.Date;

public class ReproductionCutting
{
	  private Basis basisId;
	  private Date date;

	  //
	  // getters / setters
	  //
	  public Basis getBasisId()
	  {
	    return this.basisId;
	  }

	  public void setBasisId(Basis basisId)
	  {
	    this.basisId = basisId;
	  }

	  public Date getDate()
	  {
	    return this.date;
	  }

	  public void setDate(Date date)
	  {
	    this.date = date;
	  }

	  public boolean equals(Object obj)
	  {
	    if (this == obj)
	    {
	      return true;
	    }

	    if (null == obj)
	    {
	      return false;
	    }

	    if (obj instanceof ReproductionCutting == false)
	    {
	      return false;
	    }

	    ReproductionCutting other = (ReproductionCutting) obj;

	    if (basisId != other.basisId)
	    {
	      return false;
	    }

	    if (false == date.equals(other.date))
	    {
	      return false;
	    }

	    return true;
	  }

	  public int hashCode()
	  {
	    int result = 29;

	    result = (29 * result) + basisId.hashCode();
	    result = (29 * result) + date.hashCode();

	    return result;
	  }

	  public String toString()
	  {
	    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("ReproductionCutting")
	                                                               .append("(");

	    buffer.append("[").append("basisId").append("=").append(basisId).append("]");
	    buffer.append("[").append("date").append("=").append(date).append("]");

	    return buffer.append(")").toString();
	  }
}
