// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.util.Date;

import org.unibl.etf.dao.interfaces.DAOFactory;

public class ReproductionCutting {
	public ReproductionCutting(Basis basis, Date date, Integer produces, Integer takeARoot, Integer basisId) {
		this.basis = basis;
		this.date = date;
		this.produces = produces;
		this.takeARoot = takeARoot;
		this.basisId = basisId;
	}

	private Basis basis;
	private Date date;
	private Integer produces;
	private Integer takeARoot;
	private Integer basisId;

	public ReproductionCutting() {

	}

	//
	// getters / setters
	//
	public Integer getBasisId() {
		return basisId;
	}

	public void setBasisId(Integer basisId) {
		this.basisId = basisId;
		basis = null;
	}

	public Basis getBasis() {
		if (basis == null) {
			basis = DAOFactory.getInstance().getBasisDAO().getByPrimaryKey(basisId);
		}
		return this.basis;
	}

	public void setBasis(Basis basisId) {
		this.basis = basisId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getProduces() {
		return produces;
	}

	public void setProduces(Integer produces) {
		this.produces = produces;
	}

	public Integer getTakeARoot() {
		return takeARoot;
	}

	public void setTakeARoot(Integer takeARoot) {
		this.takeARoot = takeARoot;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((basisId == null) ? 0 : basisId.hashCode());
		result = prime * result + ((date == null) ? 0 : date.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ReproductionCutting other = (ReproductionCutting) obj;
		if (basisId == null) {
			if (other.basisId != null)
				return false;
		} else if (!basisId.equals(other.basisId))
			return false;
		if (date == null) {
			if (other.date != null)
				return false;
		} else if (!date.equals(other.date))
			return false;
		return true;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("ReproductionCutting")
				.append("(");

		buffer.append("[").append("basisId").append("=").append(basisId).append("]");
		buffer.append("[").append("produces").append("=").append(produces).append("]");
		buffer.append("[").append("takeARoot").append("=").append(takeARoot).append("]");
		buffer.append("[").append("date").append("=").append(date).append("]");

		return buffer.append(")").toString();
	}
}
