// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.math.BigDecimal;

import org.unibl.etf.dao.interfaces.DAOFactory;

public class SaleItem {
	public SaleItem() {
		super();
	}

	public SaleItem(Integer count, Plant plant, Sale sale, Integer plantId, Integer saleId, BigDecimal price,
			BigDecimal heightMin) {
		super();
		this.count = count;
		this.plant = plant;
		this.sale = sale;
		this.plantId = plantId;
		this.saleId = saleId;
		this.price = price;
		this.heightMin = heightMin;
	}

	private Integer count;
	private Plant plant;
	private Sale sale;
	private Integer plantId;
	private Integer saleId;
	private BigDecimal price;
	private BigDecimal heightMin;
	//
	// getters / setters
	//

	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Plant getPlant() {
		if (plant == null) {
			plant = DAOFactory.getInstance().getPlantDAO().getAllByPrimaryKey(plantId);
		}
		return plant;
	}

	public void setPlant(Plant plant) {
		this.plant = plant;
	}

	public Sale getSale() {
		if (sale == null) {
			sale = DAOFactory.getInstance().getSaleDAO().getByPrimaryKey(saleId);
		}
		return sale;
	}

	public void setSale(Sale sale) {
		this.sale = sale;
	}

	public Integer getPlantId() {
		return plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
		plant = null;
	}

	public Integer getSaleId() {
		return saleId;
	}

	public void setSaleId(Integer saleId) {
		this.saleId = saleId;
		sale = null;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((plantId == null) ? 0 : plantId.hashCode());
		result = prime * result + ((saleId == null) ? 0 : saleId.hashCode());
		result = prime * result + ((heightMin == null) ? 0 : heightMin.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SaleItem other = (SaleItem) obj;
		if (plantId == null) {
			if (other.plantId != null)
				return false;
		} else if (!plantId.equals(other.plantId))
			return false;
		if (saleId == null) {
			if (other.saleId != null)
				return false;
		} else if (!saleId.equals(other.saleId))
			return false;
		if (heightMin == null) {
			if (other.heightMin != null)
				return false;
		} else if (!heightMin.equals(other.heightMin))
			return false;
		return true;
	}

	public String toString() {
		return plant.getScientificName() + " [" + heightMin + "]cm - " + count + " kom - " + price + " KM";
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getHeightMin() {
		return heightMin;
	}

	public void setHeightMin(BigDecimal heightMin) {
		this.heightMin = heightMin;
	}

}
