// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.io.Serializable;


public class SaleItemId implements Serializable
{
  private int pricelistId;
  private int plantId;
  private int saleId;

  //
  // getters / setters
  //
  public int getPricelistId()
  {
    return this.pricelistId;
  }

  public void setPricelistId(int pricelistId)
  {
    this.pricelistId = pricelistId;
  }

  public int getPlantId()
  {
    return this.plantId;
  }

  public void setPlantId(int plantId)
  {
    this.plantId = plantId;
  }

  public int getSaleId()
  {
    return this.saleId;
  }

  public void setSaleId(int saleId)
  {
    this.saleId = saleId;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof SaleItemId == false)
    {
      return false;
    }

    SaleItemId other = (SaleItemId) obj;

    if (pricelistId != other.pricelistId)
    {
      return false;
    }

    if (plantId != other.plantId)
    {
      return false;
    }

    if (saleId != other.saleId)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + pricelistId;
    result = (29 * result) + plantId;
    result = (29 * result) + saleId;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("SaleItemId").append("(");

    buffer.append("[").append("pricelistId").append("=").append(pricelistId).append("]");
    buffer.append("[").append("plantId").append("=").append(plantId).append("]");
    buffer.append("[").append("saleId").append("=").append(saleId).append("]");

    return buffer.append(")").toString();
  }
}
