// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class SaleItem
{
  private Integer count;

  public Integer getCount() {
	return count;
}

public void setCount(Integer count) {
	this.count = count;
}

private Pricelist pricelistId;
  private Plant plantId;
  private Sale saleId;

  //
  // getters / setters
  //
  public Pricelist getPricelistId()
  {
    return this.pricelistId;
  }

  public void setPricelistId(Pricelist pricelistId)
  {
    this.pricelistId = pricelistId;
  }

  public Plant getPlantId()
  {
    return this.plantId;
  }

  public void setPlantId(Plant plantId)
  {
    this.plantId = plantId;
  }

  public Sale getSaleId()
  {
    return this.saleId;
  }

  public void setSaleId(Sale saleId)
  {
    this.saleId = saleId;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof SaleItem == false)
    {
      return false;
    }

    SaleItem other = (SaleItem) obj;

    if (pricelistId != other.pricelistId)
    {
      return false;
    }

    if (plantId != other.plantId)
    {
      return false;
    }

    if (saleId != other.saleId)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + pricelistId.hashCode();
    result = (29 * result) + plantId.hashCode();
    result = (29 * result) + saleId.hashCode();

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("SaleItem").append("(");

    buffer.append("[").append("pricelistId").append("=").append(pricelistId).append("]");
    buffer.append("[").append("plantId").append("=").append(plantId).append("]");
    buffer.append("[").append("saleId").append("=").append(saleId).append("]");
    buffer.append("[").append("count").append("=").append(count).append("]");

    return buffer.append(")").toString();
  }
  
}
