// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class SaleItem
{
  private SaleItemId id;
  private int count;

  //
  // getters / setters
  //
  public SaleItemId getId()
  {
    return this.id;
  }

  public void setId(SaleItemId id)
  {
    this.id = id;
  }

  public int getCount()
  {
    return this.count;
  }

  public void setCount(int count)
  {
    this.count = count;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof SaleItem == false)
    {
      return false;
    }

    SaleItem other = (SaleItem) obj;

    if (false == id.equals(other.id))
    {
      return false;
    }

    if (count != other.count)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + id.hashCode();
    result = (29 * result) + count;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("SaleItem").append("(");

    buffer.append("[").append("id").append("=").append(id).append("]");
    buffer.append("[").append("count").append("=").append(count).append("]");

    return buffer.append(")").toString();
  }
}
