// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.math.BigDecimal;

import java.util.Date;

public class Sale {
	private Integer saleId;
	private Date date;
	private BigDecimal price;
	private Boolean paidOff;
	private Customer customer;
	private Integer customerId;

	//
	// getters / setters
	//
	public Integer getSaleId() {
		return this.saleId;
	}

	public void setSaleId(Integer saleId) {
		this.saleId = saleId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal amount) {
		this.price = amount;
	}

	public Boolean getPaidOff() {
		return this.paidOff;
	}

	public void setPaidOff(Boolean paidOff) {
		this.paidOff = paidOff;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customerId) {
		this.customer = customerId;
	}

	public Integer getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((saleId == null) ? 0 : saleId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Sale other = (Sale) obj;
		if (saleId == null) {
			if (other.saleId != null)
				return false;
		} else if (!saleId.equals(other.saleId))
			return false;
		return true;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Sale").append("(");

		buffer.append("[").append("saleId").append("=").append(saleId).append("]");
		buffer.append("[").append("date").append("=").append(date).append("]");
		buffer.append("[").append("amount").append("=").append(price).append("]");
		buffer.append("[").append("paidOff").append("=").append(paidOff).append("]");
		buffer.append("[").append("customerId").append("=").append(customerId).append("]");

		return buffer.append(")").toString();
	}
}
