// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.util.Date;


public class Task
{
  private int taskId;
  private Date dateFrom;
  private Date dateTo;
  private byte done;
  private int regionId;
  private int plantMaintanceActivityId;

  //
  // getters / setters
  //
  public int getTaskId()
  {
    return this.taskId;
  }

  public void setTaskId(int taskId)
  {
    this.taskId = taskId;
  }

  public Date getDateFrom()
  {
    return this.dateFrom;
  }

  public void setDateFrom(Date dateFrom)
  {
    this.dateFrom = dateFrom;
  }

  public Date getDateTo()
  {
    return this.dateTo;
  }

  public void setDateTo(Date dateTo)
  {
    this.dateTo = dateTo;
  }

  public byte getDone()
  {
    return this.done;
  }

  public void setDone(byte done)
  {
    this.done = done;
  }

  public int getRegionId()
  {
    return this.regionId;
  }

  public void setRegionId(int regionId)
  {
    this.regionId = regionId;
  }

  public int getPlantMaintanceActivityId()
  {
    return this.plantMaintanceActivityId;
  }

  public void setPlantMaintanceActivityId(int plantMaintanceActivityId)
  {
    this.plantMaintanceActivityId = plantMaintanceActivityId;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Task == false)
    {
      return false;
    }

    Task other = (Task) obj;

    if (taskId != other.taskId)
    {
      return false;
    }

    if (false == dateFrom.equals(other.dateFrom))
    {
      return false;
    }

    if (false == dateTo.equals(other.dateTo))
    {
      return false;
    }

    if (done != other.done)
    {
      return false;
    }

    if (regionId != other.regionId)
    {
      return false;
    }

    if (plantMaintanceActivityId != other.plantMaintanceActivityId)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + taskId;
    result = (29 * result) + dateFrom.hashCode();
    result = (29 * result) + dateTo.hashCode();
    result = (29 * result) + (int) done;
    result = (29 * result) + regionId;
    result = (29 * result) + plantMaintanceActivityId;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Task").append("(");

    buffer.append("[").append("taskId").append("=").append(taskId).append("]");
    buffer.append("[").append("dateFrom").append("=").append(dateFrom).append("]");
    buffer.append("[").append("dateTo").append("=").append(dateTo).append("]");
    buffer.append("[").append("done").append("=").append(done).append("]");
    buffer.append("[").append("regionId").append("=").append(regionId).append("]");
    buffer.append("[").append("plantMaintanceActivityId").append("=").append(plantMaintanceActivityId)
          .append("]");

    return buffer.append(")").toString();
  }
}
