// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.unibl.etf.dao.interfaces.DAOFactory;

public class Task {
	private Integer taskId;
	private Integer planId;
	private Plan plan;
	private Date dateFrom;
	private Date dateTo;
	private Boolean done;
	private Integer regionId;
	private Region region;
	private Boolean deleted;
	private Integer plantMaintanceActivityId;
	private PlantMaintanceActivity plantMaintanceActivity;

	//
	// getters / setters
	//
	
	public Task() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	public Integer getTaskId() {
		return this.taskId;
	}

	public Task(Integer taskId, Integer planId, Plan plan, Date dateFrom, Date dateTo, Boolean done, Integer regionId,
			Region region, Boolean deleted, Integer plantMaintanceActivityId,
			PlantMaintanceActivity plantMaintanceActivity) {
		super();
		this.taskId = taskId;
		this.planId = planId;
		this.plan = plan;
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
		this.done = done;
		this.regionId = regionId;
		this.region = region;
		this.deleted = deleted;
		this.plantMaintanceActivityId = plantMaintanceActivityId;
		this.plantMaintanceActivity = plantMaintanceActivity;
	}

	public Integer getPlanId() {
		return planId;
	}

	public void setPlanId(Integer planId) {
		this.planId = planId;
	}

	public Plan getPlan() {
		if(plan==null) {
			plan = DAOFactory.getInstance().getPlanDAO().getByPrimaryKey(planId);
		}
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	public Boolean getDone() {
		return this.done;
	}

	public void setDone(Boolean done) {
		this.done = done;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Region getRegion() {
		if (region == null) {
			region = DAOFactory.getInstance().getRegionDAO().getByPrimaryKey(regionId);

		}
		return this.region;
	}

	public void setRegion(Region regionId) {
		this.region = regionId;
	}

	public PlantMaintanceActivity getPlantMaintanceActivity() {
		if (plantMaintanceActivity == null) {
			plantMaintanceActivity = DAOFactory.getInstance().getPlantMaintanceActivityDAO()
					.getByPrimaryKey(plantMaintanceActivityId);
		}
		return this.plantMaintanceActivity;
	}

	public void setPlantMaintanceActivity(PlantMaintanceActivity plantMaintanceActivityId) {
		this.plantMaintanceActivity = plantMaintanceActivityId;
	}

	public Integer getRegionId() {
		return regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
		region = null;
	}

	public Integer getPlantMaintanceActivityId() {
		return plantMaintanceActivityId;
	}

	public void setPlantMaintanceActivityId(Integer plantMaintanceActivityId) {
		this.plantMaintanceActivityId = plantMaintanceActivityId;
		plantMaintanceActivity = null;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Task other = (Task) obj;
		if (taskId == null) {
			if (other.taskId != null)
				return false;
		} else if (!taskId.equals(other.taskId))
			return false;
		return true;
	}

	public String toString() {
		DateFormat df = new SimpleDateFormat("dd.MM.yyyy.");
		return this.plantMaintanceActivity.getActivity() + " " + df.format(this.getDateFrom());
	}
}
