// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.util.Date;

import org.unibl.etf.dao.interfaces.DAOException;
import org.unibl.etf.dao.interfaces.DAOFactory;

public class Task {
	private Integer taskId;
	private Date dateFrom;
	private Date dateTo;
	private Boolean done;
	private Integer regionId;
	private Region region;
	private Boolean isDeleted;
	private Integer plantMaintanceActivityId;
	private PlantMaintanceActivity plantMaintanceActivity;

	//
	// getters / setters
	//
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	public Boolean getDone() {
		return this.done;
	}

	public void setDone(Boolean done) {
		this.done = done;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Region getRegion() {
		if (region == null) {
			region = DAOFactory.getInstance().getRegionDAO().getByPrimaryKey(regionId);

		}
		return this.region;
	}

	public void setRegion(Region regionId) {
		this.region = regionId;
	}

	public PlantMaintanceActivity getPlantMaintanceActivity() {
		if (plantMaintanceActivity == null) {
			try {
				plantMaintanceActivity = DAOFactory.getInstance().getPlantMaintanceActivityDAO()
						.getByPrimaryKey(plantMaintanceActivityId);
			} catch (DAOException e) {
				e.printStackTrace();
			}
		}
		return this.plantMaintanceActivity;
	}

	public void setPlantMaintanceActivity(PlantMaintanceActivity plantMaintanceActivityId) {
		this.plantMaintanceActivity = plantMaintanceActivityId;
	}

	public Integer getRegionId() {
		return regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
		region = null;
	}

	public Integer getPlantMaintanceActivityId() {
		return plantMaintanceActivityId;
	}

	public void setPlantMaintanceActivityId(Integer plantMaintanceActivityId) {
		this.plantMaintanceActivityId = plantMaintanceActivityId;
		plantMaintanceActivity = null;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Task other = (Task) obj;
		if (taskId == null) {
			if (other.taskId != null)
				return false;
		} else if (!taskId.equals(other.taskId))
			return false;
		return true;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Task").append("(");

		buffer.append("[").append("taskId").append("=").append(taskId).append("]");
		buffer.append("[").append("dateFrom").append("=").append(dateFrom).append("]");
		buffer.append("[").append("dateTo").append("=").append(dateTo).append("]");
		buffer.append("[").append("done").append("=").append(done).append("]");
		buffer.append("[").append("isDeleted").append("=").append(isDeleted).append("]");
		buffer.append("[").append("regionId").append("=").append(regionId).append("]");
		buffer.append("[").append("plantMaintanceActivityId").append("=").append(plantMaintanceActivityId).append("]");

		return buffer.append(")").toString();
	}
}
