// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class Tool {
	private Integer toolId;
	private String toolName;
	private Integer count;

	//
	// getters / setters
	//
	public Integer getToolId() {
		return this.toolId;
	}

	public void setToolId(Integer toolId) {
		this.toolId = toolId;
	}

	public String getToolName() {
		return this.toolName;
	}

	public void setToolName(String toolName) {
		this.toolName = toolName;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((toolId == null) ? 0 : toolId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Tool other = (Tool) obj;
		if (toolId == null) {
			if (other.toolId != null)
				return false;
		} else if (!toolId.equals(other.toolId))
			return false;
		return true;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Tool").append("(");

		buffer.append("[").append("toolId").append("=").append(toolId).append("]");
		buffer.append("[").append("toolName").append("=").append(toolName).append("]");
		buffer.append("[").append("count").append("=").append(count).append("]");

		return buffer.append(")").toString();
	}

	public Tool(Integer toolId, String toolName, Integer count) {
		super();
		this.toolId = toolId;
		this.toolName = toolName;
		this.count = count;
	}

	public Tool() {
		super();
		// TODO Auto-generated constructor stub
	}
}
