// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class Tool { //promijenjen toString, dodani konstruktori
	private Integer toolId;
	private String toolName;
	private Integer count;
	private Boolean isMachine;
	private Boolean deleted;

	//
	// getters / setters
	//
	public Integer getToolId() {
		return this.toolId;
	}

	public void setToolId(Integer toolId) {
		this.toolId = toolId;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public String getToolName() {
		return this.toolName;
	}

	public void setToolName(String toolName) {
		this.toolName = toolName;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Boolean getIsMachine() {
		return this.isMachine;
	}

	public void setIsMachine(Boolean isMachine) {
		this.isMachine = isMachine;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((toolId == null) ? 0 : toolId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Tool other = (Tool) obj;
		if (toolId == null) {
			if (other.toolId != null)
				return false;
		} else if (!toolId.equals(other.toolId))
			return false;
		return true;
	}

	public String toString() {
		return toolName;
	}



	public Tool(Integer toolId, String toolName, Integer count, Boolean isMachine) {
		super();
		this.toolId = toolId;
		this.toolName = toolName;
		this.count = count;
		this.isMachine = isMachine;
	}

	public Tool() {
		super();
		// TODO Auto-generated constructor stub
	}
}
