// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.util.Date;


public class ToolItem
{
  private Integer toolItemId;
  private Date nextServiceDate;
  private Boolean isMachine;
  private Tool toolId;
  private Condition conditionId;

  //
  // getters / setters
  //
  public Integer getToolItemId()
  {
    return this.toolItemId;
  }

  public void setToolItemId(Integer toolItemId)
  {
    this.toolItemId = toolItemId;
  }

  public Date getNextServiceDate()
  {
    return this.nextServiceDate;
  }

  public void setNextServiceDate(Date nextServiceDate)
  {
    this.nextServiceDate = nextServiceDate;
  }

  public Boolean getIsMachine()
  {
    return this.isMachine;
  }

  public void setIsMachine(Boolean isMachine)
  {
    this.isMachine = isMachine;
  }

  public Tool getToolId()
  {
    return this.toolId;
  }

  public void setToolId(Tool toolId)
  {
    this.toolId = toolId;
  }

  public Condition getConditionId()
  {
    return this.conditionId;
  }

  public void setConditionId(Condition conditionId)
  {
    this.conditionId = conditionId;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof ToolItem == false)
    {
      return false;
    }

    ToolItem other = (ToolItem) obj;

    if (toolItemId != other.toolItemId)
    {
      return false;
    }

    if (false == nextServiceDate.equals(other.nextServiceDate))
    {
      return false;
    }

    if (isMachine != other.isMachine)
    {
      return false;
    }

    if (toolId != other.toolId)
    {
      return false;
    }

    if (conditionId != other.conditionId)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + toolItemId;
    result = (29 * result) + nextServiceDate.hashCode();
    result = (29 * result) + isMachine.hashCode();
    result = (29 * result) + toolId.hashCode();
    result = (29 * result) + conditionId.hashCode();

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("ToolItem").append("(");

    buffer.append("[").append("toolItemId").append("=").append(toolItemId).append("]");
    buffer.append("[").append("nextServiceDate").append("=").append(nextServiceDate).append("]");
    buffer.append("[").append("isMachine").append("=").append(isMachine).append("]");
    buffer.append("[").append("toolId").append("=").append(toolId).append("]");
    buffer.append("[").append("conditionId").append("=").append(conditionId).append("]");

    return buffer.append(")").toString();
  }
}
