// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

public class Tool
{
  private Integer toolId;
  private String toolName;
  private Integer count;

  //
  // getters / setters
  //
  public Integer getToolId()
  {
    return this.toolId;
  }

  public void setToolId(Integer toolId)
  {
    this.toolId = toolId;
  }

  public String getToolName()
  {
    return this.toolName;
  }

  public void setToolName(String toolName)
  {
    this.toolName = toolName;
  }

  public Integer getCount()
  {
    return this.count;
  }

  public void setCount(Integer count)
  {
    this.count = count;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Tool == false)
    {
      return false;
    }

    Tool other = (Tool) obj;

    if (toolId != other.toolId)
    {
      return false;
    }

    if (false == toolName.equals(other.toolName))
    {
      return false;
    }

    if (count != other.count)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + toolId;
    result = (29 * result) + toolName.hashCode();
    result = (29 * result) + count;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Tool").append("(");

    buffer.append("[").append("toolId").append("=").append(toolId).append("]");
    buffer.append("[").append("toolName").append("=").append(toolName).append("]");
    buffer.append("[").append("count").append("=").append(count).append("]");

    return buffer.append(")").toString();
  }
}
