// Generated by DB Solo 5.2.3 on Jan 11, 2018 at 3:37:10 PM
package org.unibl.etf.dto;

import java.math.BigDecimal;


public class Transaction
{
  private int transactionId;
  private BigDecimal amount;
  private byte type;

  //
  // getters / setters
  //
  public int getTransactionId()
  {
    return this.transactionId;
  }

  public void setTransactionId(int transactionId)
  {
    this.transactionId = transactionId;
  }

  public BigDecimal getAmount()
  {
    return this.amount;
  }

  public void setAmount(BigDecimal amount)
  {
    this.amount = amount;
  }

  public byte getType()
  {
    return this.type;
  }

  public void setType(byte type)
  {
    this.type = type;
  }

  public boolean equals(Object obj)
  {
    if (this == obj)
    {
      return true;
    }

    if (null == obj)
    {
      return false;
    }

    if (obj instanceof Transaction == false)
    {
      return false;
    }

    Transaction other = (Transaction) obj;

    if (transactionId != other.transactionId)
    {
      return false;
    }

    if (false == amount.equals(other.amount))
    {
      return false;
    }

    if (type != other.type)
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    int result = 29;

    result = (29 * result) + transactionId;
    result = (29 * result) + amount.hashCode();
    result = (29 * result) + (int) type;

    return result;
  }

  public String toString()
  {
    StringBuffer buffer = new StringBuffer("org.unibl.etf.dto").append(".").append("Transaction").append("(");

    buffer.append("[").append("transactionId").append("=").append(transactionId).append("]");
    buffer.append("[").append("amount").append("=").append(amount).append("]");
    buffer.append("[").append("type").append("=").append(type).append("]");

    return buffer.append(")").toString();
  }
}
